In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [21]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [22]:
np.array(a)

array([1. , 2. , 3.5])

In [23]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [26]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
arr = np.linspace(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Random

In [12]:
np.random.rand(5)

array([0.41460551, 0.94401718, 0.18545352, 0.5802633 , 0.21221462])

In [21]:
np.random.randint(10,20,6)

array([11, 19, 11, 18, 12, 14], dtype=int32)

In [23]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.shape

(3, 3)

In [26]:
arr.size

9

Array Methods

In [28]:
arr.min()

np.int64(1)

In [29]:
arr.max()

np.int64(9)

In [30]:
arr.sum()

np.int64(45)

In [31]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [33]:
arr.mean()

np.float64(5.0)

In [34]:
arr.std()

np.float64(2.581988897471611)

In [35]:
arr.argmax()

np.int64(8)

In [40]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])