In [1]:
import numpy as np

ARRAY OPERATIONS

Arithmetic Operations

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [6]:
a1+a2

array([ 7,  9, 11, 13, 15])

Broadcasting

In [10]:
l = [10,20,30,40]
arr = np.array(l)

In [9]:
arr+10

array([20, 30, 40, 50])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow Copy

In [14]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = a[:5]
slice*5

array([ 5, 10, 15, 20, 25])

In [19]:
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
b[0]=51
b

array([51,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [7]:
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [9]:
A@B

array([[19, 22],
       [43, 50]])

In [10]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [11]:
A.T

array([[1, 3],
       [2, 4]])

Stacking Array

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [13]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [7]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [11]:
d = np.vsplit(c,2)

In [12]:
for i in d:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
